appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: aHBBL/K29oQExSyOQR5c6hwiLG+FWzsl+PIutgiJUwhvEaRO643/aNeLXSwTYzr6Xmd4qxRRD0M/SHnquxzpVzgwFFFBJ7aifUEij3XB2lDpyfYFqLBXHBjUvGHH3/CpBX33pBIns+dEmE7c/2M1MdC73EUfzOvb8F34dLZ49PQSJ/iHwasvMktNdsNQUgjNx2V7lD04BGg7fl5dKmPNn2hlDummbwhsylQSGM2s1yfc/3Rnno3p1lFCOfoTCDZjrDFVr3GMOiuAV4+OYL2ZE23d7lONg+TNVrelefHH56EKLl8B+xPqZ2orNPvIg1/j7bKVkOkHBovt4qvLJhpmxQFKXVzg9934vGcU8MepUCLmUxgOWdcbUYRLZz0y2tYygOPXIEfsKEgw4iud8SZmvqcny8mQiThRadMLq7M645oMkc3TR0rKc4Nxo6WtVt/ly7SS9XCP9GVRFdfrUeeI3TRC9inW0OKq/zb219WETcr/SdgIxrtYPcnO0s6aGRwdJ5e/mM6LR9GQ/pLPl6CST6JdPFgJ94NMjYv8W5+SatDlyCdlyckuuCCYZnRwaF0B7E90kDLxzHC2WpP4Yp1E0TzL7LL+jnS4kVJ+rMA4gZQsC7TeO5Dcdwy+5zG7x0uOnptFCO4emBTQX0nbPkW08/8NSXsDDEfRR1tAfYI5P94=}
bot:
  automerge: true
